version: '3.7'

services:
  api:
    container_name: sdws-api
    build:
        context: api
        dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    networks:
      - sdws-network
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      WWWGROUP: '${WWWGROUP:-1000}'
    depends_on:
        - postgres
  frontend:
    container_name: sdws-frontend
    build:
        context: ./frontend
        dockerfile: Dockerfile
    networks:
      - sdws-network
  postgres:
    container_name: sdws-postgres
    image: debezium/postgres:15-alpine
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    networks:
      - sdws-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sdws_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  nginx:
    container_name: sdws-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - sdws-network
    depends_on:
        - api
        - frontend
        - postgres
networks:
  sdws-network:
    driver: bridge
volumes:
    postgres_data: