#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER swarm-drone-websystem
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/composer install --no-interaction --no-scripts --working-dir=/var/www/html

    # Check the exit code of the previous command
    composer_exit_code=$?
    if [ $composer_exit_code -eq 0 ]; then
        echo "Composer install completed successfully."
        
    else
        echo "Composer install failed. Exit code: $composer_exit_code"
        exit $composer_exit_code
    fi

    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
