name: Frontend CI

on:
  push:
    branches: [master]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yaml'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        working-directory: frontend
      - run: cp .env.example .env
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/lampspace/sdws-frontend:latest