name: Pineline

on:
    push:
      branches: [master]
jobs:
    changes:
        name: Changes
        runs-on: ubuntu-latest
        outputs:
            api: ${{ steps.changes.outputs.api }}
            frontend: ${{ steps.changes.outputs.frontend }}
        steps:
            - uses: actions/checkout@v3
            - uses: dorny/paths-filter@v2
              id: changes
              with:
                filters: |
                  api:
                    - 'api/**'
                  frontend:
                    - 'frontend/**'
    api-build:
        needs: changes
        if: ${{ needs.changes.outputs.api == 'true' }}
        name: API Build
        runs-on: ubuntu-latest
        outputs:
            api: ${{ steps.api-ci.outputs.result }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.1'
                extensions: mbstring, zip, pcntl, pdo_mysql
            - name: Install API dependencies
              run: composer install --prefer-dist --no-progress --no-interaction
              working-directory: api
            - name: Copy API .env
              run: cp .env.example .env
              working-directory: api
            - name: Generate API key
              run: php artisan key:generate
              working-directory: api
            - name: Log in to the Container registry
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.TOKEN }}
            - name: Build and push API Docker image
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: docker/build-push-action@v3
              with:
                context: ./api
                push: true
                tags: ghcr.io/lampspace/sdws-api:latest
            - id: api-ci
              run: echo "result=success" >> $GITHUB_OUTPUT

    frontend-build:
        needs: changes
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        name: Frontend Build
        runs-on: ubuntu-latest
        outputs:
            frontend: ${{ steps.frontend-ci.outputs.result }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: Install frontend dependencies
              run: npm ci
              working-directory: frontend
            - name: Copy frontend .env
              run: cp .env.example .env
              working-directory: frontend
            - name: Build frontend
              run: npm run build
              working-directory: frontend
            - name: Log in to the Container registry
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.TOKEN }}
            - name: Build and push frontend Docker image
              if: ${{ github.ref == 'refs/heads/master' }}
              uses: docker/build-push-action@v3
              with:
                context: ./frontend
                push: true
                tags: ghcr.io/lampspace/sdws-frontend:latest
            - id: frontend-ci
              run: echo "result=success" >> $GITHUB_OUTPUT

    deployment:
        name: Deployment
        runs-on: ubuntu-latest
        needs: [api-build, frontend-build]
        if: ${{ needs.api-build.outputs.api == 'success' || needs.frontend-build.outputs.frontend == 'success' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: SSH Docker Compose
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
                port: ${{ secrets.SSH_PORT }}
                
                script: |
                    cd /home/ngtrdai/swarm-drones-web-system/
                    git pull
                    cp api/.env.prod api/.env
                    docker-compose down
                    docker-compose up -d